### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by AlisdairO** [aturon/crossbeam#58] opened 2016-03-06 14:45 UTC
The following code appears to leak memory - topping out at 430MB after the loop finishes.  If Vec::with_capacity(0) is used instead, no memory is leaked.  Of course it's entirely possible that I'm using crossbeam incorrectly - if so  and you could point me in the right direction I'd be most grateful :-).

```
extern crate crossbeam;
use std::sync::atomic::Ordering::{Acquire, Release};
use crossbeam::mem::epoch::{self, Atomic, Owned};

fn main() {
    for _ in 0..2000000000 {
        let guard = epoch::pin();
        let vec: Atomic<Vec<u32>> = Atomic::null();
        vec.store(Some(Owned::new(Vec::with_capacity(1))), Release);
        if let Some(tab_shr) = vec.load(Acquire, &guard) {
            vec.store(None, Release);
            unsafe {
                guard.unlinked(tab_shr);
            }   
        }   
    }   
    println!("done");
    let _ = std::io::stdin().read_line(&mut String::new());
}
```

**Comment by aturon** [comment] 2016-03-06 15:50
Note that you have two allocations going on here: `Owned::new` and `Vec::with_capacity`. Crossbeam is correctly freeing the first allocation, but the second is being leaked.

The reason is that, while crossbeam frees the memory it allocates, it does *not* run destructors. The [blog post](http://aturon.github.io/blog/2015/08/27/epoch/) has more details. For many concurrent data structures, interior data is moved out (via `ptr::read`) when `unlinked` is called -- again, the blog post has examples like this. So much of the time, it's actually *vital* that dtors not run.

In general, though, I do want to [add destructor execution](https://github.com/aturon/crossbeam/issues/13), though it's not as simple as you might imagine. Aside from the fact that some of the data should not have dtors run, the portion that does effectively has to have a `'static` bound, since the dtor can run at an arbitrary time after `unlinked` is called.

I'm actually doing some work on precisely this topic right now, as part of a separate branch.

For the time being, I'm going to close this as a dupe of #13 -- effectively, a request for crossbeam to have the option of running destructors.

**Closed by aturon** 2016-03-06 15:50 UTC

**Comment by AlisdairO** [comment] 2016-03-06 20:49
Righto, that explains that!  Thanks a lot for the explanation :-).
